#include "engine/menu_runtime_launch.hpp"

namespace eon {

RuntimeCandidateLaunchResult launch_runtime_candidate(const std::optional<LaunchRequest>& candidate,
    const std::vector<ReleaseArchive>& releases, ReleaseRuntimeCoordinator& coordinator) {
    const auto gate = admit_runtime_launch(coordinator, candidate, releases);
    if (!gate.accepted() || !coordinator.active()) return {gate.admission, gate.rejection, std::nullopt};
    return {gate.admission, gate.rejection, *coordinator.active()};
}

RuntimeCandidateLaunchResult LauncherRuntimeController::launch_direct(
    const LaunchRequest& candidate, const std::vector<ReleaseArchive>& releases) {
    return launch_runtime_candidate(candidate, releases, coordinator_);
}

RuntimeCandidateLaunchResult LauncherRuntimeController::launch_menu(
    const LauncherSessionState& session, const LaunchRequest& base,
    const std::vector<ReleaseArchive>& releases) {
    return launch_runtime_candidate(session.launch_request(base), releases, coordinator_);
}

bool LauncherRuntimeController::requires_revocation_for(const LauncherSourceIdentity& source) const {
    if (!coordinator_.active()) return false;
    const auto& launch = *coordinator_.active();
    return LauncherSourceIdentity{launch.release.game, launch.release.platform, launch.release.language,
        launch.release.sha256} != source;
}

void LauncherRuntimeController::reset() {
    coordinator_.reset();
}

RuntimeInputDisposition LauncherRuntimeController::observe_input(
    const RuntimeInputObservation& observation) {
    return coordinator_.observe_input(observation);
}

std::optional<MillenniumDosPresentationSnapshot>
LauncherRuntimeController::millennium_dos_presentation() const {
    return coordinator_.millennium_dos_presentation();
}

std::optional<MillenniumDosStartupInputSnapshot>
LauncherRuntimeController::millennium_dos_startup_input() const {
    return coordinator_.millennium_dos_startup_input();
}
MillenniumDosSoundDriverLoadObservationResult LauncherRuntimeController::observe_millennium_dos_sound_driver_load(MillenniumDosSoundDriverLoadObservation o){return coordinator_.observe_millennium_dos_sound_driver_load(std::move(o));}
std::optional<MillenniumDosSoundDriverLoadCheckpoint> LauncherRuntimeController::millennium_dos_sound_driver_load_checkpoint()const{return coordinator_.millennium_dos_sound_driver_load_checkpoint();}
std::optional<MillenniumDosCompatibilityRunnerCheckpoint> LauncherRuntimeController::tick_millennium_dos_compatibility_runner(){return coordinator_.tick_millennium_dos_compatibility_runner();}
MillenniumDosTitleExecEntryObservationResult LauncherRuntimeController::observe_millennium_dos_title_child_process_entry(MillenniumDosTitleExecProcessEntry o){return coordinator_.observe_millennium_dos_title_child_process_entry(o);}
MillenniumDosTitleExecEntryObservationResult LauncherRuntimeController::advance_millennium_dos_title_entry_prefix(MillenniumDosTitleExecPrefixObservation o){return coordinator_.advance_millennium_dos_title_entry_prefix(o);}
std::optional<MillenniumDosTitleExecEntryRuntimeCheckpoint> LauncherRuntimeController::millennium_dos_title_exec_entry_checkpoint()const{return coordinator_.millennium_dos_title_exec_entry_checkpoint();}
MillenniumDosTitleInitializationObservationResult LauncherRuntimeController::observe_millennium_dos_title_private_interrupt_result(MillenniumDosTitlePrivateInterruptResultObservation o){return coordinator_.observe_millennium_dos_title_private_interrupt_result(o);}
MillenniumDosTitleInitializationObservationResult LauncherRuntimeController::observe_millennium_dos_title_selected_callee_result(MillenniumDosTitleSelectedCalleeResultObservation o){return coordinator_.observe_millennium_dos_title_selected_callee_result(o);}
MillenniumDosTitleInitializationObservationResult LauncherRuntimeController::observe_millennium_dos_title_bios_result(MillenniumDosTitleBiosResultObservation o){return coordinator_.observe_millennium_dos_title_bios_result(o);}
MillenniumDosTitleInitializationObservationResult LauncherRuntimeController::observe_millennium_dos_title_dos_memory_result(MillenniumDosTitleDosResultObservation o){return coordinator_.observe_millennium_dos_title_dos_memory_result(o);}
MillenniumDosTitleInitializationObservationResult LauncherRuntimeController::observe_millennium_dos_title_dos_file_result(MillenniumDosTitleDosFileResultObservation o){return coordinator_.observe_millennium_dos_title_dos_file_result(o);}
MillenniumDosTitleInitializationObservationResult LauncherRuntimeController::observe_millennium_dos_title_dos_vector_result(MillenniumDosTitleDosVectorResultObservation o){return coordinator_.observe_millennium_dos_title_dos_vector_result(o);}
MillenniumDosTitleInitializationObservationResult LauncherRuntimeController::observe_millennium_dos_title_setup_bios_result(MillenniumDosTitleSetupBiosResultObservation o){return coordinator_.observe_millennium_dos_title_setup_bios_result(o);}
MillenniumDosTitleInitializationObservationResult LauncherRuntimeController::observe_millennium_dos_title_far_words(MillenniumDosTitleFarWordsObservation o){return coordinator_.observe_millennium_dos_title_far_words(o);}
MillenniumDosTitleInitializationObservationResult LauncherRuntimeController::observe_millennium_dos_title_far_word(MillenniumDosTitleFarWordObservation o){return coordinator_.observe_millennium_dos_title_far_word(o);}
MillenniumDosTitleInitializationObservationResult LauncherRuntimeController::observe_millennium_dos_title_far_byte(MillenniumDosTitleFarByteObservation o){return coordinator_.observe_millennium_dos_title_far_byte(o);}
MillenniumDosTitleModeTwoDriveResult LauncherRuntimeController::drive_millennium_dos_title_mode_two(MillenniumDosTitleModeTwoDriveRequest r){return coordinator_.drive_millennium_dos_title_mode_two(r);}

MillenniumDosTitleToGameObservationResult LauncherRuntimeController::observe_millennium_dos_title_to_game_call_return(MillenniumDosTitleToGameCallReturnObservation o){return coordinator_.observe_millennium_dos_title_to_game_call_return(o);}
MillenniumDosTitleToGameObservationResult LauncherRuntimeController::observe_millennium_dos_title_to_game_stack_word(MillenniumDosTitleToGameStackWordObservation o){return coordinator_.observe_millennium_dos_title_to_game_stack_word(o);}
MillenniumDosTitleToGameObservationResult LauncherRuntimeController::observe_millennium_dos_title_to_game_title_termination(MillenniumDosTitleToGameInterruptObservation o){return coordinator_.observe_millennium_dos_title_to_game_title_termination(o);}
MillenniumDosTitleToGameObservationResult LauncherRuntimeController::observe_millennium_dos_title_to_game_parent_exec_return(MillenniumDosTitleToGameInterruptObservation o){return coordinator_.observe_millennium_dos_title_to_game_parent_exec_return(o);}
MillenniumDosTitleToGameObservationResult LauncherRuntimeController::observe_millennium_dos_title_to_game_child_status(MillenniumDosTitleToGameInterruptObservation o){return coordinator_.observe_millennium_dos_title_to_game_child_status(o);}
std::optional<MillenniumDosTitleToGameCheckpoint> LauncherRuntimeController::millennium_dos_title_to_game_checkpoint()const{return coordinator_.millennium_dos_title_to_game_checkpoint();}

std::optional<MillenniumDosStaticDispatchDiagnostics>
LauncherRuntimeController::millennium_dos_static_dispatch_diagnostics() const {
    return coordinator_.millennium_dos_static_dispatch_diagnostics();
}

std::optional<MillenniumDosNativeProcessCheckpoint>
LauncherRuntimeController::millennium_dos_native_process_checkpoint() const {
    return coordinator_.millennium_dos_native_process_checkpoint();
}

MillenniumDosGxActiveTraceAdmission
LauncherRuntimeController::admit_active_millennium_dos_gx_startup_reference_trace(
    const ReferenceTrace& trace) {
    return coordinator_.admit_active_millennium_dos_gx_startup_reference_trace(trace);
}

std::optional<MillenniumDosGxStartupCheckpoint>
LauncherRuntimeController::millennium_dos_gx_startup_checkpoint() const {
    return coordinator_.millennium_dos_gx_startup_checkpoint();
}

MillenniumDosPostOverlayObservationResult
LauncherRuntimeController::observe_millennium_dos_post_overlay_private_interrupt_return(
    const MillenniumDosPostOverlayPrivateInterruptReturnObservation observation) {
    return coordinator_.observe_millennium_dos_post_overlay_private_interrupt_return(observation);
}

MillenniumDosPostOverlayObservationResult
LauncherRuntimeController::observe_millennium_dos_post_overlay_call_return(
    const MillenniumDosPostOverlayCallReturnObservation observation) {
    return coordinator_.observe_millennium_dos_post_overlay_call_return(observation);
}

MillenniumDosPostOverlayObservationResult
LauncherRuntimeController::observe_millennium_dos_post_overlay_al(
    const MillenniumDosPostOverlayAlObservation observation) {
    return coordinator_.observe_millennium_dos_post_overlay_al(observation);
}

MillenniumDosPostOverlayObservationResult
LauncherRuntimeController::observe_millennium_dos_post_overlay_runtime_byte(
    const MillenniumDosPostOverlayRuntimeByteObservation observation) {
    return coordinator_.observe_millennium_dos_post_overlay_runtime_byte(observation);
}

std::optional<MillenniumDosPostOverlayLoopCheckpoint>
LauncherRuntimeController::millennium_dos_post_overlay_loop_checkpoint() const {
    return coordinator_.millennium_dos_post_overlay_loop_checkpoint();
}
MillenniumDosPostOverlayObservationResult LauncherRuntimeController::complete_millennium_dos_handler(const MillenniumDosHandlerCompletionObservation o){return coordinator_.complete_millennium_dos_handler(o);}
std::optional<MillenniumDosHandlerCompletionCheckpoint> LauncherRuntimeController::millennium_dos_handler_completion_checkpoint()const{return coordinator_.millennium_dos_handler_completion_checkpoint();}

#define EON_LAUNCHER_TENTH_PROXY(name, type) \
MillenniumDosTenthFunctionObservationResult LauncherRuntimeController::name( \
    const type observation) { return coordinator_.name(observation); }
EON_LAUNCHER_TENTH_PROXY(observe_millennium_dos_tenth_function_dispatch, MillenniumDosTenthFunctionDispatchObservation)
EON_LAUNCHER_TENTH_PROXY(observe_millennium_dos_tenth_function_word, MillenniumDosTenthFunctionWordObservation)
EON_LAUNCHER_TENTH_PROXY(observe_millennium_dos_tenth_function_byte, MillenniumDosTenthFunctionByteObservation)
EON_LAUNCHER_TENTH_PROXY(observe_millennium_dos_tenth_function_call_return, MillenniumDosTenthFunctionCallReturnObservation)
EON_LAUNCHER_TENTH_PROXY(observe_millennium_dos_tenth_function_zero_flag, MillenniumDosTenthFunctionZeroFlagObservation)
EON_LAUNCHER_TENTH_PROXY(observe_millennium_dos_tenth_function_bl, MillenniumDosTenthFunctionBlObservation)
#undef EON_LAUNCHER_TENTH_PROXY

std::optional<MillenniumDosTenthFunctionCheckpoint>
LauncherRuntimeController::millennium_dos_tenth_function_checkpoint() const {
    return coordinator_.millennium_dos_tenth_function_checkpoint();
}

#define EON_LAUNCHER_SEVENTH_PROXY(name, type) \
MillenniumDosSeventhFunctionObservationResult LauncherRuntimeController::name( \
    const type observation) { return coordinator_.name(observation); }
EON_LAUNCHER_SEVENTH_PROXY(observe_millennium_dos_seventh_function_dispatch, MillenniumDosSeventhFunctionDispatchObservation)
EON_LAUNCHER_SEVENTH_PROXY(observe_millennium_dos_seventh_function_word, MillenniumDosSeventhFunctionWordObservation)
EON_LAUNCHER_SEVENTH_PROXY(observe_millennium_dos_seventh_function_byte, MillenniumDosSeventhFunctionByteObservation)
EON_LAUNCHER_SEVENTH_PROXY(observe_millennium_dos_seventh_function_call_return, MillenniumDosSeventhFunctionCallReturnObservation)
EON_LAUNCHER_SEVENTH_PROXY(observe_millennium_dos_seventh_function_returned_bx, MillenniumDosSeventhFunctionReturnedBxObservation)
#undef EON_LAUNCHER_SEVENTH_PROXY

std::optional<MillenniumDosSeventhFunctionCheckpoint>
LauncherRuntimeController::millennium_dos_seventh_function_checkpoint() const {
    return coordinator_.millennium_dos_seventh_function_checkpoint();
}
#define EON_LAUNCH_HELPER(name,type) MillenniumDosSharedHelperObservationResult LauncherRuntimeController::name(const type o){return coordinator_.name(o);}
EON_LAUNCH_HELPER(observe_millennium_dos_shared_helper_entry,MillenniumDosSharedHelperEntryObservation) EON_LAUNCH_HELPER(observe_millennium_dos_shared_helper_word,MillenniumDosSharedHelperWordObservation) EON_LAUNCH_HELPER(observe_millennium_dos_shared_helper_far_word,MillenniumDosSharedHelperFarWordObservation) EON_LAUNCH_HELPER(observe_millennium_dos_shared_helper_call_return,MillenniumDosSharedHelperCallReturnObservation) EON_LAUNCH_HELPER(observe_millennium_dos_shared_helper_external_return,MillenniumDosSharedHelperExternalReturnObservation)
#undef EON_LAUNCH_HELPER
std::optional<MillenniumDosSharedHelperCheckpoint>LauncherRuntimeController::millennium_dos_shared_helper_checkpoint()const{return coordinator_.millennium_dos_shared_helper_checkpoint();}
MillenniumDosSharedHelperObservationResult LauncherRuntimeController::observe_millennium_dos_special_action_helper_entry(const MillenniumDosSpecialActionHelperEntryObservation o){return coordinator_.observe_millennium_dos_special_action_helper_entry(o);} MillenniumDosSharedHelperObservationResult LauncherRuntimeController::observe_millennium_dos_special_action_external_return(const MillenniumDosSharedHelperExternalReturnObservation o){return coordinator_.observe_millennium_dos_special_action_external_return(o);}
#define EON_LAUNCH_GX_ADAPTER(name,type) MillenniumDosGxAdapterObservationResult LauncherRuntimeController::name(const type o){return coordinator_.name(o);}
EON_LAUNCH_GX_ADAPTER(observe_millennium_dos_second_special_action_adapter_entry,MillenniumDosGxAdapterEntryObservation) EON_LAUNCH_GX_ADAPTER(observe_millennium_dos_gx_adapter_segment,MillenniumDosGxAdapterWordObservation) EON_LAUNCH_GX_ADAPTER(observe_millennium_dos_gx_adapter_transfer,MillenniumDosGxAdapterTransferObservation) EON_LAUNCH_GX_ADAPTER(observe_millennium_dos_gx_adapter_overlay_return,MillenniumDosGxAdapterReturnObservation) EON_LAUNCH_GX_ADAPTER(observe_millennium_dos_gx_adapter_return,MillenniumDosGxAdapterReturnObservation) EON_LAUNCH_GX_ADAPTER(observe_millennium_dos_second_special_action_return,MillenniumDosGxAdapterReturnObservation)
#undef EON_LAUNCH_GX_ADAPTER
std::optional<MillenniumDosGxAdapterCheckpoint> LauncherRuntimeController::millennium_dos_gx_adapter_checkpoint()const{return coordinator_.millennium_dos_gx_adapter_checkpoint();}

#define EON_LAUNCHER_SIXTH_PROXY(name, type) \
MillenniumDosSixthFunctionObservationResult LauncherRuntimeController::name( \
    const type observation) { return coordinator_.name(observation); }
EON_LAUNCHER_SIXTH_PROXY(observe_millennium_dos_sixth_function_dispatch, MillenniumDosSixthFunctionDispatchObservation)
EON_LAUNCHER_SIXTH_PROXY(observe_millennium_dos_sixth_function_word, MillenniumDosSixthFunctionWordObservation)
EON_LAUNCHER_SIXTH_PROXY(observe_millennium_dos_sixth_function_byte, MillenniumDosSixthFunctionByteObservation)
EON_LAUNCHER_SIXTH_PROXY(observe_millennium_dos_sixth_function_call_return, MillenniumDosSixthFunctionCallReturnObservation)
EON_LAUNCHER_SIXTH_PROXY(observe_millennium_dos_sixth_function_bl, MillenniumDosSixthFunctionBlObservation)
#undef EON_LAUNCHER_SIXTH_PROXY
MillenniumDosSixthFunctionObservationResult LauncherRuntimeController::begin_millennium_dos_sixth_function_restoration(){return coordinator_.begin_millennium_dos_sixth_function_restoration();}
MillenniumDosSixthFunctionObservationResult LauncherRuntimeController::begin_millennium_dos_sixth_function_caller_helper_prefix(){return coordinator_.begin_millennium_dos_sixth_function_caller_helper_prefix();}

std::optional<MillenniumDosSixthFunctionCheckpoint>
LauncherRuntimeController::millennium_dos_sixth_function_checkpoint() const {
    return coordinator_.millennium_dos_sixth_function_checkpoint();
}

#define EON_LAUNCHER_EIGHTH_PROXY(name, type) \
MillenniumDosEighthFunctionObservationResult LauncherRuntimeController::name( \
    const type observation) { return coordinator_.name(observation); }
EON_LAUNCHER_EIGHTH_PROXY(observe_millennium_dos_eighth_function_dispatch,
    MillenniumDosEighthFunctionDispatchObservation)
EON_LAUNCHER_EIGHTH_PROXY(observe_millennium_dos_eighth_function_call_return,
    MillenniumDosEighthFunctionCallReturnObservation)
EON_LAUNCHER_EIGHTH_PROXY(observe_millennium_dos_eighth_function_bl,
    MillenniumDosEighthFunctionBlObservation)
#undef EON_LAUNCHER_EIGHTH_PROXY

std::optional<MillenniumDosEighthFunctionCheckpoint>
LauncherRuntimeController::millennium_dos_eighth_function_checkpoint() const {
    return coordinator_.millennium_dos_eighth_function_checkpoint();
}
#define EON_LAUNCHER_NINTH(name,type) MillenniumDosNinthFunctionObservationResult LauncherRuntimeController::name(const type o) { return coordinator_.name(o); }
EON_LAUNCHER_NINTH(observe_millennium_dos_ninth_function_dispatch,MillenniumDosNinthFunctionDispatchObservation)
EON_LAUNCHER_NINTH(observe_millennium_dos_ninth_function_word,MillenniumDosNinthFunctionWordObservation)
EON_LAUNCHER_NINTH(observe_millennium_dos_ninth_function_byte,MillenniumDosNinthFunctionByteObservation)
EON_LAUNCHER_NINTH(observe_millennium_dos_ninth_function_call_return,MillenniumDosNinthFunctionCallReturnObservation)
#undef EON_LAUNCHER_NINTH
std::optional<MillenniumDosNinthFunctionCheckpoint> LauncherRuntimeController::millennium_dos_ninth_function_checkpoint() const { return coordinator_.millennium_dos_ninth_function_checkpoint(); }
#define EON_LAUNCH_F9H(name,type) MillenniumDosNinthHandoffObservationResult LauncherRuntimeController::name(type o){return coordinator_.name(o);}
EON_LAUNCH_F9H(observe_millennium_dos_ninth_handoff_entry,MillenniumDosNinthHandoffEntryObservation) EON_LAUNCH_F9H(observe_millennium_dos_ninth_handoff_byte,MillenniumDosNinthHandoffByteObservation) EON_LAUNCH_F9H(observe_millennium_dos_ninth_handoff_word,MillenniumDosNinthHandoffWordObservation) EON_LAUNCH_F9H(observe_millennium_dos_ninth_handoff_call_return,MillenniumDosNinthHandoffCallReturnObservation) EON_LAUNCH_F9H(observe_millennium_dos_ninth_handoff_zero_flag,MillenniumDosNinthHandoffZeroFlagObservation) EON_LAUNCH_F9H(observe_millennium_dos_ninth_handoff_bl,MillenniumDosNinthHandoffBlObservation)
#undef EON_LAUNCH_F9H
std::optional<MillenniumDosNinthHandoffCheckpoint> LauncherRuntimeController::millennium_dos_ninth_handoff_checkpoint()const{return coordinator_.millennium_dos_ninth_handoff_checkpoint();}
#define EON_LAUNCHER_FOURTH(n,t) MillenniumDosFourthFunctionObservationResult LauncherRuntimeController::n(t o){return coordinator_.n(o);}
EON_LAUNCHER_FOURTH(observe_millennium_dos_fourth_function_dispatch,MillenniumDosFourthFunctionDispatchObservation)
EON_LAUNCHER_FOURTH(observe_millennium_dos_fourth_function_word,MillenniumDosFourthFunctionWordObservation)
EON_LAUNCHER_FOURTH(observe_millennium_dos_fourth_function_call_return,MillenniumDosFourthFunctionCallReturnObservation)
#undef EON_LAUNCHER_FOURTH
std::optional<MillenniumDosFourthFunctionCheckpoint> LauncherRuntimeController::millennium_dos_fourth_function_checkpoint()const{return coordinator_.millennium_dos_fourth_function_checkpoint();}
MillenniumDosFifthFunctionObservationResult LauncherRuntimeController::observe_millennium_dos_fifth_function_dispatch(MillenniumDosFifthFunctionDispatchObservation o){return coordinator_.observe_millennium_dos_fifth_function_dispatch(o);} MillenniumDosFifthFunctionObservationResult LauncherRuntimeController::observe_millennium_dos_fifth_function_call_return(MillenniumDosFifthFunctionCallReturnObservation o){return coordinator_.observe_millennium_dos_fifth_function_call_return(o);} std::optional<MillenniumDosFifthFunctionCheckpoint> LauncherRuntimeController::millennium_dos_fifth_function_checkpoint()const{return coordinator_.millennium_dos_fifth_function_checkpoint();}
#define EON_LAUNCHER_THIRD(name,type) MillenniumDosThirdFunctionObservationResult LauncherRuntimeController::name(type o){return coordinator_.name(o);}
EON_LAUNCHER_THIRD(observe_millennium_dos_third_function_dispatch,MillenniumDosThirdFunctionDispatchObservation)
EON_LAUNCHER_THIRD(observe_millennium_dos_third_function_word,MillenniumDosThirdFunctionWordObservation)
EON_LAUNCHER_THIRD(observe_millennium_dos_third_function_call_return,MillenniumDosThirdFunctionCallReturnObservation)
EON_LAUNCHER_THIRD(observe_millennium_dos_third_function_bl,MillenniumDosThirdFunctionBlObservation)
#undef EON_LAUNCHER_THIRD
std::optional<MillenniumDosThirdFunctionCheckpoint> LauncherRuntimeController::millennium_dos_third_function_checkpoint()const{return coordinator_.millennium_dos_third_function_checkpoint();}
#define EON_LAUNCHER_FIRST(name,type) MillenniumDosFirstFunctionObservationResult LauncherRuntimeController::name(type o){return coordinator_.name(o);}
EON_LAUNCHER_FIRST(observe_millennium_dos_first_function_dispatch,MillenniumDosFirstFunctionDispatchObservation)
EON_LAUNCHER_FIRST(observe_millennium_dos_first_function_call_return,MillenniumDosFirstFunctionCallReturnObservation)
EON_LAUNCHER_FIRST(observe_millennium_dos_first_function_bl,MillenniumDosFirstFunctionBlObservation)
#undef EON_LAUNCHER_FIRST
std::optional<MillenniumDosFirstFunctionCheckpoint> LauncherRuntimeController::millennium_dos_first_function_checkpoint()const{return coordinator_.millennium_dos_first_function_checkpoint();}
#define EON_LAUNCHER_SECOND(name,type) MillenniumDosSecondFunctionObservationResult LauncherRuntimeController::name(type o){return coordinator_.name(o);}
EON_LAUNCHER_SECOND(observe_millennium_dos_second_function_dispatch,MillenniumDosSecondFunctionDispatchObservation)
EON_LAUNCHER_SECOND(observe_millennium_dos_second_function_runtime_byte,MillenniumDosSecondFunctionRuntimeByteObservation)
EON_LAUNCHER_SECOND(observe_millennium_dos_second_function_call_return,MillenniumDosSecondFunctionCallReturnObservation)
EON_LAUNCHER_SECOND(observe_millennium_dos_second_function_bl,MillenniumDosSecondFunctionBlObservation)
#undef EON_LAUNCHER_SECOND
std::optional<MillenniumDosSecondFunctionCheckpoint> LauncherRuntimeController::millennium_dos_second_function_checkpoint()const{return coordinator_.millennium_dos_second_function_checkpoint();}
#define EON_LAUNCHER_F2_CALLBACK(name,type) MillenniumDosSecondFunctionCallbackObservationResult LauncherRuntimeController::name(type o){return coordinator_.name(o);}
EON_LAUNCHER_F2_CALLBACK(observe_millennium_dos_second_function_callback_entry,MillenniumDosSecondFunctionCallbackEntryObservation)
EON_LAUNCHER_F2_CALLBACK(observe_millennium_dos_second_function_callback_runtime_byte,MillenniumDosSecondFunctionCallbackRuntimeByteObservation)
EON_LAUNCHER_F2_CALLBACK(observe_millennium_dos_second_function_callback_runtime_word,MillenniumDosSecondFunctionCallbackRuntimeWordObservation)
EON_LAUNCHER_F2_CALLBACK(observe_millennium_dos_second_function_callback_call_return,MillenniumDosSecondFunctionCallbackCallReturnObservation)
EON_LAUNCHER_F2_CALLBACK(observe_millennium_dos_second_function_callback_bl,MillenniumDosSecondFunctionCallbackBlObservation)
EON_LAUNCHER_F2_CALLBACK(observe_millennium_dos_second_function_callback_jump_entry,MillenniumDosSecondFunctionCallbackJumpEntryObservation)
EON_LAUNCHER_F2_CALLBACK(observe_millennium_dos_second_function_callback_external_return,MillenniumDosSecondFunctionCallbackExternalReturnObservation)
#undef EON_LAUNCHER_F2_CALLBACK
std::optional<MillenniumDosSecondFunctionCallbackCheckpoint> LauncherRuntimeController::millennium_dos_second_function_callback_checkpoint()const{return coordinator_.millennium_dos_second_function_callback_checkpoint();}
std::optional<NativeRuntimeMemoryCheckpoint> LauncherRuntimeController::native_runtime_memory_checkpoint()const{return coordinator_.native_runtime_memory_checkpoint();}
std::optional<DeuterosAmigaTitlePlanarPatchSnapshot> LauncherRuntimeController::deuteros_amiga_title_planar_patch()const{return coordinator_.deuteros_amiga_title_planar_patch();}
std::optional<DeuterosAmigaTitlePlanarSurfaceSnapshot> LauncherRuntimeController::deuteros_amiga_title_planar_surface()const{return coordinator_.deuteros_amiga_title_planar_surface();}
std::optional<NativeRuntimeMemoryDiagnostics> LauncherRuntimeController::native_runtime_memory_diagnostics()const{return coordinator_.native_runtime_memory_diagnostics();}
#define EON_LAUNCH_BDF(name,type) MillenniumDosBdfObservationResult LauncherRuntimeController::name(type o){return coordinator_.name(o);}
EON_LAUNCH_BDF(observe_millennium_dos_bdf_byte,MillenniumDosBdfByteObservation) EON_LAUNCH_BDF(observe_millennium_dos_bdf_word,MillenniumDosBdfWordObservation) EON_LAUNCH_BDF(observe_millennium_dos_bdf_poll_return,MillenniumDosBdfPollReturnObservation)
EON_LAUNCH_BDF(observe_millennium_dos_bdf_mapping_return,MillenniumDosBdfMappingReturnObservation)
EON_LAUNCH_BDF(observe_millennium_dos_bdf_far_byte,MillenniumDosBdfFarByteObservation)
EON_LAUNCH_BDF(observe_millennium_dos_bdf_external_return,MillenniumDosBdfExternalReturnObservation)
EON_LAUNCH_BDF(observe_millennium_dos_bdf_terminal_jump,MillenniumDosBdfTerminalJumpObservation)
EON_LAUNCH_BDF(observe_millennium_dos_bdf_mode_two_byte,MillenniumDosBdfByteObservation)
EON_LAUNCH_BDF(observe_millennium_dos_bdf_mode_two_word,MillenniumDosBdfWordObservation)
EON_LAUNCH_BDF(observe_millennium_dos_bdf_mode_two_far_word,MillenniumDosBdfModeTwoFarWordObservation)
EON_LAUNCH_BDF(observe_millennium_dos_bdf_mode_two_far_byte,MillenniumDosBdfModeTwoFarByteObservation)
EON_LAUNCH_BDF(observe_millennium_dos_bdf_mode_two_external_return,MillenniumDosBdfExternalReturnObservation)
EON_LAUNCH_BDF(observe_millennium_dos_bdf_other_mode_byte,MillenniumDosBdfByteObservation)
EON_LAUNCH_BDF(observe_millennium_dos_bdf_other_mode_word,MillenniumDosBdfWordObservation)
EON_LAUNCH_BDF(observe_millennium_dos_bdf_other_mode_external_return,MillenniumDosBdfExternalReturnObservation)
EON_LAUNCH_BDF(observe_millennium_dos_bdf_other_mode_far_word,MillenniumDosBdfModeTwoFarWordObservation)
EON_LAUNCH_BDF(observe_millennium_dos_bdf_other_mode_far_byte,MillenniumDosBdfModeTwoFarByteObservation)
#undef EON_LAUNCH_BDF
std::optional<MillenniumDosBdfCheckpoint>LauncherRuntimeController::millennium_dos_bdf_checkpoint()const{return coordinator_.millennium_dos_bdf_checkpoint();}
std::optional<MillenniumDosOwnedFunctionDiagnostics>
LauncherRuntimeController::millennium_dos_owned_function_diagnostics() const {
    return coordinator_.millennium_dos_owned_function_diagnostics();
}

std::optional<DeuterosAmigaVmEvents> LauncherRuntimeController::tick_deuteros_amiga_opening() {
    return coordinator_.tick_deuteros_amiga_opening();
}

std::optional<std::vector<float>>
LauncherRuntimeController::render_deuteros_amiga_opening_audio(const std::size_t frames) {
    return coordinator_.render_deuteros_amiga_opening_audio(frames);
}

std::optional<DeuterosAmigaOpeningCheckpoint>
LauncherRuntimeController::deuteros_amiga_opening_checkpoint() const {
    return coordinator_.deuteros_amiga_opening_checkpoint();
}

std::optional<DeuterosAmigaOpeningPresentationSnapshot>
LauncherRuntimeController::deuteros_amiga_opening_presentation() const {
    return coordinator_.deuteros_amiga_opening_presentation();
}

std::optional<DeuterosAmigaTitleStageBoundarySnapshot>
LauncherRuntimeController::deuteros_amiga_title_stage_boundary() const {
    return coordinator_.deuteros_amiga_title_stage_boundary();
}

std::optional<DeuterosAmigaTitleDependencyChainCheckpoint>
LauncherRuntimeController::deuteros_amiga_title_dependency_chain_checkpoint() const {
    return coordinator_.deuteros_amiga_title_dependency_chain_checkpoint();
}
#define EON_LAUNCHER_DEUTEROS_TITLE(name,signature,arg) DeuterosAmigaTitleDependencyObservationResult LauncherRuntimeController::name signature { return coordinator_.name arg; }
EON_LAUNCHER_DEUTEROS_TITLE(advance_deuteros_amiga_title_local_prefix,(),())
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_exec_return,(const DeuterosAmigaObservedExecReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_open_library_return,(const DeuterosAmigaObservedOpenLibraryReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(advance_deuteros_amiga_title_post_open_library_local_path,(),())
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_display_base,(const DeuterosAmigaObservedDisplayBaseRead o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_custom_chip_write,(const DeuterosAmigaObservedCustomChipWrite o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_callback_exec_return,(const DeuterosAmigaObservedCallbackExecReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_service_setup_exec_return,(const DeuterosAmigaObservedServiceSetupExecReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_second_service_exec_return,(const DeuterosAmigaObservedServiceSetupExecReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_third_service_exec_return,(const DeuterosAmigaObservedServiceSetupExecReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_fourth_service_exec_return,(const DeuterosAmigaObservedServiceSetupExecReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_fifth_service_exec_return,(const DeuterosAmigaObservedServiceSetupExecReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(advance_deuteros_amiga_title_controller_pointer_seed,(),())
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_service_batch_graphics_return,(const DeuterosAmigaObservedGraphicsVectorReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_service_batch_runtime_word,(const DeuterosAmigaObservedServiceWordRead o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_graphics_service_first_return,(const DeuterosAmigaObservedGraphicsVectorReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_graphics_service_second_return,(const DeuterosAmigaObservedGraphicsVectorReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_graphics_service_third_return,(const DeuterosAmigaObservedGraphicsVectorReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_tail_first_graphics_return,(const DeuterosAmigaObservedGraphicsVectorReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_tail_copy_words,(const DeuterosAmigaObservedTailCopyWords o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_tail_selection_words,(const DeuterosAmigaObservedTailSelectionWords o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_tail_second_graphics_return,(const DeuterosAmigaObservedGraphicsVectorReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_tail_repeated_selection_words,(const DeuterosAmigaObservedTailSelectionWords o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_tail_repeated_graphics_return,(const DeuterosAmigaObservedGraphicsVectorReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_tail_repeated_wrapper_graphics_return,(const DeuterosAmigaObservedGraphicsVectorReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_tail_source_table,(const DeuterosAmigaObservedTailSourceTable o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_tail_exec_return,(const DeuterosAmigaObservedTailExecReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_load_service_return,(const DeuterosAmigaObservedLocalCallReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_load_selector,(const DeuterosAmigaObservedLoadSelector o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_load_copy_chunk,(const DeuterosAmigaObservedLoadCopyChunk o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_load_dispatch_table_base,(const DeuterosAmigaObservedLoadDispatchTableBase o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_load_dispatch_table_word,(const DeuterosAmigaObservedLoadDispatchTableWord o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_command_opcode,(const DeuterosAmigaObservedTitleCommandOpcode o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_command_operand_byte,(const DeuterosAmigaObservedTitleCommandOperandByte o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_command_pointer_long,(const DeuterosAmigaObservedTitleCommandPointerLong o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_command_eight_pointer,(const DeuterosAmigaObservedTitleCommandEightPointer o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_command_eight_mode,(const DeuterosAmigaObservedTitleCommandEightMode o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_command_eight_scale,(const DeuterosAmigaObservedTitleCommandEightScale o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_command_call_return,(const DeuterosAmigaObservedTitleCommandCallReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_command_planar_write,(const DeuterosAmigaObservedTitleCommandPlanarWrite o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_command_planar_variant_write,(const DeuterosAmigaObservedTitleCommandPlanarVariantWrite o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_command_negative_service,(const DeuterosAmigaObservedTitleCommandNegativeService o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_post_command_pointer_route,(const DeuterosAmigaObservedTitlePostCommandPointerRoute o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_post_command_graphics_return,(const DeuterosAmigaObservedGraphicsVectorReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(advance_deuteros_amiga_title_post_command_first_dispatch,(),())
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_post_command_first_dispatch_header,(const DeuterosAmigaObservedTitleFirstDispatchHeader o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(advance_deuteros_amiga_title_post_command_first_dispatch_packet,(),())
EON_LAUNCHER_DEUTEROS_TITLE(advance_deuteros_amiga_title_post_command_first_dispatch_decode,(),())
EON_LAUNCHER_DEUTEROS_TITLE(advance_deuteros_amiga_title_post_command_first_dispatch_caller_tail,(),())
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_post_command_first_dispatch_destination_words,(const DeuterosAmigaObservedTitleFirstDispatchDestinationWords o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(advance_deuteros_amiga_title_post_command_second_dispatch,(),())
EON_LAUNCHER_DEUTEROS_TITLE(advance_deuteros_amiga_title_post_command_second_dispatch_decode,(),())
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_post_command_second_dispatch_destination_words,(const DeuterosAmigaObservedTitleSecondDispatchDestinationWords o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(advance_deuteros_amiga_title_post_command_service_route_prefix,(),())
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_post_command_service_first_return,(const DeuterosAmigaObservedLocalCallReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_post_command_service_second_return,(const DeuterosAmigaObservedLocalCallReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_post_command_service_third_return,(const DeuterosAmigaObservedLocalCallReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_post_command_nested_words,(const DeuterosAmigaObservedTitlePostCommandNestedWords o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_post_command_nested_call_return,(const DeuterosAmigaObservedLocalCallReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(advance_deuteros_amiga_title_post_command_nested_loop,(),())
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_post_command_continuation_return,(const DeuterosAmigaObservedLocalCallReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_post_command_pointer_chain,(const DeuterosAmigaObservedTitlePostCommandPointerChain o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_post_command_dispatch_destination,(const DeuterosAmigaObservedTitlePostCommandDispatchDestination o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(advance_deuteros_amiga_title_post_command_selected_stream,(),())
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_post_command_descriptor_call_return,(const DeuterosAmigaObservedLocalCallReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(advance_deuteros_amiga_title_post_command_descriptor_loop,(),())
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_post_command_descriptor_byte,(const DeuterosAmigaObservedTitlePostCommandDescriptorByte o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_post_command_adjusted_dispatch_destination,(const DeuterosAmigaObservedTitlePostCommandAdjustedDispatchDestination o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_post_adjusted_caller_pointer,(const DeuterosAmigaObservedTitlePostAdjustedCallerPointer o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_post_adjusted_object_gate,(const DeuterosAmigaObservedTitlePostAdjustedObjectGate o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_post_adjusted_first_helper_return,(const DeuterosAmigaObservedLocalCallReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_post_adjusted_second_helper_return,(const DeuterosAmigaObservedLocalCallReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_post_adjusted_rts_frame,(const DeuterosAmigaObservedTitlePostAdjustedRtsFrame o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_post_adjusted_repeated_nested_words,(const DeuterosAmigaObservedTitlePostCommandNestedWords o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_post_adjusted_repeated_nested_call_return,(const DeuterosAmigaObservedLocalCallReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(advance_deuteros_amiga_title_post_adjusted_repeated_nested_loop,(),())
EON_LAUNCHER_DEUTEROS_TITLE(advance_deuteros_amiga_title_post_adjusted_caller_indirect,(),())
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_post_adjusted_caller_indirect_return,(const DeuterosAmigaObservedTitlePostAdjustedIndirectReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_post_adjusted_caller_37180_return,(const DeuterosAmigaObservedTitlePostAdjusted37180Return o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_post_adjusted_mode_return,(const DeuterosAmigaObservedLocalCallReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_post_adjusted_222c0_return,(const DeuterosAmigaObservedLocalCallReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_post_adjusted_timer_state,(const DeuterosAmigaObservedTitlePostAdjustedTimerState o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_post_adjusted_4069a_return,(const DeuterosAmigaObservedLocalCallReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_post_adjusted_join_byte,(const DeuterosAmigaObservedTitlePostAdjustedJoinByte o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_post_adjusted_1f9a4_return,(const DeuterosAmigaObservedLocalCallReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_post_adjusted_1fe88_return,(const DeuterosAmigaObservedTitlePostAdjusted1fe88Return o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_post_adjusted_final_gate,(const DeuterosAmigaObservedTitlePostAdjustedFinalGate o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_post_adjusted_input_return,(const DeuterosAmigaObservedTitlePostAdjustedInputReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_post_adjusted_repeated_input_return,(const DeuterosAmigaObservedLocalCallReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_tail_copy,(const DeuterosAmigaObservedTitleTailCopy o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(advance_deuteros_amiga_title_tail_subroutine,(),())
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_tail_initial_service_return,(const DeuterosAmigaObservedLocalCallReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_tail_exec_return,(const DeuterosAmigaObservedTitleTailExecReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_tail_compare_longs,(const DeuterosAmigaObservedTitleTailCompareLongs o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_title_tail_controller_long,(const DeuterosAmigaObservedTitleTailControllerLong o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(advance_deuteros_amiga_title_profile_two_bootstrap,(),())
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_main_stage_reentry_d0,(const DeuterosAmigaObservedMainStageReentryD0 o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_main_stage_first_exec_return,(const DeuterosAmigaObservedMainStageExecReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_main_stage_second_exec_return,(const DeuterosAmigaObservedMainStageExecReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_main_stage_first_local_return,(const DeuterosAmigaObservedLocalCallReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_main_stage_pointer_service_return,(const DeuterosAmigaObservedMainStagePointerServiceReturn o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_main_stage_audio_setup,(const DeuterosAmigaObservedMainStageAudioSetup o),(o))
EON_LAUNCHER_DEUTEROS_TITLE(advance_deuteros_amiga_main_stage_20994_exec_entry,(),())
EON_LAUNCHER_DEUTEROS_TITLE(observe_deuteros_amiga_main_stage_2099e_exec_return,(const DeuterosAmigaObservedMainStageExecReturn o),(o))
#undef EON_LAUNCHER_DEUTEROS_TITLE

DeuterosAmigaTitleDisplayTraceAdmission
LauncherRuntimeController::admit_active_deuteros_amiga_title_display_trace(
    const ReferenceTrace& trace) {
    return coordinator_.admit_active_deuteros_amiga_title_display_trace(trace);
}

std::optional<DeuterosAmigaTitleDisplayTraceCheckpoint>
LauncherRuntimeController::deuteros_amiga_title_display_trace_checkpoint() const {
    return coordinator_.deuteros_amiga_title_display_trace_checkpoint();
}

std::optional<DeuterosAtariBootstrapCheckpoint>
LauncherRuntimeController::deuteros_atari_bootstrap_checkpoint() const {
    return coordinator_.deuteros_atari_bootstrap_checkpoint();
}

std::optional<DeuterosAtariBootstrapPresentationSnapshot>
LauncherRuntimeController::deuteros_atari_bootstrap_presentation() const {
    return coordinator_.deuteros_atari_bootstrap_presentation();
}

std::optional<MillenniumAmigaBootstrapPresentationSnapshot>
LauncherRuntimeController::millennium_amiga_bootstrap_presentation() const {
    return coordinator_.millennium_amiga_bootstrap_presentation();
}
MillenniumAmigaBootstrapRelocatorObservationResult LauncherRuntimeController::observe_millennium_amiga_bootstrap_relocator_overread(const MillenniumAmigaBootstrapRelocatorObservation o){return coordinator_.observe_millennium_amiga_bootstrap_relocator_overread(o);}
MillenniumAmigaBootstrapRelocatorObservationResult LauncherRuntimeController::observe_millennium_amiga_bootstrap_relocator_terminal_jump(const MillenniumAmigaBootstrapRelocatorObservation o){return coordinator_.observe_millennium_amiga_bootstrap_relocator_terminal_jump(o);}
MillenniumAmigaBootstrapRelocatorObservationResult LauncherRuntimeController::observe_millennium_amiga_bootstrap_setup_call_return(const MillenniumAmigaBootstrapRelocatorObservation o){return coordinator_.observe_millennium_amiga_bootstrap_setup_call_return(o);}
MillenniumAmigaBootstrapRelocatorObservationResult LauncherRuntimeController::observe_millennium_amiga_bootstrap_first_read_return(const MillenniumAmigaBootstrapRelocatorObservation o){return coordinator_.observe_millennium_amiga_bootstrap_first_read_return(o);}
MillenniumAmigaBootstrapRelocatorObservationResult LauncherRuntimeController::observe_millennium_amiga_first_stage_entry(const MillenniumAmigaFirstStageEntryObservation o){return coordinator_.observe_millennium_amiga_first_stage_entry(o);}
MillenniumAmigaBootstrapRelocatorObservationResult LauncherRuntimeController::observe_millennium_amiga_first_stage_illegal_handler(const MillenniumAmigaFirstStageIllegalHandlerObservation o){return coordinator_.observe_millennium_amiga_first_stage_illegal_handler(o);}
MillenniumAmigaBootstrapRelocatorObservationResult LauncherRuntimeController::observe_millennium_amiga_second_illegal_handler(const MillenniumAmigaSecondIllegalHandlerObservation o){return coordinator_.observe_millennium_amiga_second_illegal_handler(o);}
MillenniumAmigaBootstrapRelocatorObservationResult LauncherRuntimeController::observe_millennium_amiga_first_trace_handler(const MillenniumAmigaFirstTraceHandlerObservation o){return coordinator_.observe_millennium_amiga_first_trace_handler(o);}
MillenniumAmigaBootstrapRelocatorObservationResult LauncherRuntimeController::observe_millennium_amiga_trace_branch_chain(const MillenniumAmigaTraceBranchChainRuntimeObservation o){return coordinator_.observe_millennium_amiga_trace_branch_chain(o);}
MillenniumAmigaBootstrapRelocatorObservationResult LauncherRuntimeController::observe_millennium_amiga_trace_register_prefix(const MillenniumAmigaTraceRegisterPrefixRuntimeObservation o){return coordinator_.observe_millennium_amiga_trace_register_prefix(o);}
std::optional<MillenniumAmigaBootstrapRelocatorCheckpoint> LauncherRuntimeController::millennium_amiga_bootstrap_relocator_checkpoint()const{return coordinator_.millennium_amiga_bootstrap_relocator_checkpoint();}

std::optional<MillenniumAtariBootstrapPresentationSnapshot>
LauncherRuntimeController::millennium_atari_bootstrap_presentation() const {
    return coordinator_.millennium_atari_bootstrap_presentation();
}
MillenniumAtariConfigConsumerResult
LauncherRuntimeController::observe_millennium_atari_status_register(
    const MillenniumAtariStatusRegisterObservation observation) {
    return coordinator_.observe_millennium_atari_status_register(observation);
}
MillenniumAtariConfigConsumerResult
LauncherRuntimeController::observe_millennium_atari_xbios_selector_two(
    const MillenniumAtariXbiosSelectorTwoObservation observation) {
    return coordinator_.observe_millennium_atari_xbios_selector_two(observation);
}
MillenniumAtariConfigConsumerResult
LauncherRuntimeController::observe_millennium_atari_xbios_selector_three(
    const MillenniumAtariXbiosSelectorThreeObservation observation) {
    return coordinator_.observe_millennium_atari_xbios_selector_three(observation);
}
MillenniumAtariConfigConsumerResult
LauncherRuntimeController::observe_millennium_atari_xbios_selector_four(
    const MillenniumAtariXbiosSelectorFourObservation observation) {
    return coordinator_.observe_millennium_atari_xbios_selector_four(observation);
}
MillenniumAtariConfigConsumerResult LauncherRuntimeController::observe_millennium_atari_line_a(
    const MillenniumAtariLineAObservation observation) {
    return coordinator_.observe_millennium_atari_line_a(observation);
}

MillenniumAtariConfigConsumerResult LauncherRuntimeController::observe_millennium_atari_xbios_selector_21(
    const MillenniumAtariXbiosSelector21Observation observation) {
    return coordinator_.observe_millennium_atari_xbios_selector_21(observation);
}

MillenniumAtariConfigConsumerResult LauncherRuntimeController::observe_millennium_atari_xbios_selector_6(
    const MillenniumAtariXbiosSelector6Observation observation) {
    return coordinator_.observe_millennium_atari_xbios_selector_6(observation);
}

MillenniumAtariConfigConsumerResult LauncherRuntimeController::observe_millennium_atari_bchg_2b55a(
    const MillenniumAtariBchgObservation observation) {
    return coordinator_.observe_millennium_atari_bchg_2b55a(observation);
}

MillenniumAtariConfigConsumerResult LauncherRuntimeController::execute_millennium_atari_jsr_2b55a() {
    return coordinator_.execute_millennium_atari_jsr_2b55a();
}

MillenniumAtariConfigConsumerResult LauncherRuntimeController::execute_millennium_atari_bsr_2b59a() {
    return coordinator_.execute_millennium_atari_bsr_2b59a();
}

MillenniumAtariConfigConsumerResult LauncherRuntimeController::observe_millennium_atari_d0_indexed_byte(
    const MillenniumAtariD0IndexedByteObservation observation) {
    return coordinator_.observe_millennium_atari_d0_indexed_byte(observation);
}

MillenniumAtariConfigConsumerResult LauncherRuntimeController::execute_millennium_atari_a1_setup(){return coordinator_.execute_millennium_atari_a1_setup();}

MillenniumAtariConfigConsumerResult LauncherRuntimeController::observe_millennium_atari_d0_indexed_word(const MillenniumAtariD0IndexedWordObservation o){return coordinator_.observe_millennium_atari_d0_indexed_word(o);}

MillenniumAtariConfigConsumerResult LauncherRuntimeController::observe_millennium_atari_a0_indexed_word(const MillenniumAtariA0IndexedWordObservation o){return coordinator_.observe_millennium_atari_a0_indexed_word(o);}

MillenniumAtariConfigConsumerResult LauncherRuntimeController::execute_millennium_atari_loop_iteration_setup(){return coordinator_.execute_millennium_atari_loop_iteration_setup();}

MillenniumAtariConfigConsumerResult LauncherRuntimeController::execute_millennium_atari_loop_epilogue(){return coordinator_.execute_millennium_atari_loop_epilogue();}

MillenniumAtariConfigConsumerResult LauncherRuntimeController::observe_millennium_atari_movem_frame(const MillenniumAtariMovemFrameObservation o){return coordinator_.observe_millennium_atari_movem_frame(o);}

MillenniumAtariConfigConsumerResult LauncherRuntimeController::execute_millennium_atari_jsr_2aa68(){return coordinator_.execute_millennium_atari_jsr_2aa68();}

MillenniumAtariConfigConsumerResult LauncherRuntimeController::observe_millennium_atari_xbios_selector_38(const MillenniumAtariXbiosSelector38Observation o){return coordinator_.observe_millennium_atari_xbios_selector_38(o);}

MillenniumAtariConfigConsumerResult LauncherRuntimeController::execute_millennium_atari_jsr_2aa0c(){return coordinator_.execute_millennium_atari_jsr_2aa0c();}
MillenniumAtariConfigConsumerResult LauncherRuntimeController::observe_millennium_atari_gemdos_selector_61(const MillenniumAtariGemdosSelector61Observation o){return coordinator_.observe_millennium_atari_gemdos_selector_61(o);}
MillenniumAtariConfigConsumerResult LauncherRuntimeController::execute_millennium_atari_jsr_2a5c2(){return coordinator_.execute_millennium_atari_jsr_2a5c2();}
MillenniumAtariConfigConsumerResult LauncherRuntimeController::observe_millennium_atari_gemdos_selector_63(const MillenniumAtariGemdosSelector63Observation o){return coordinator_.observe_millennium_atari_gemdos_selector_63(o);}
MillenniumAtariConfigConsumerResult LauncherRuntimeController::observe_millennium_atari_gemdos_selector_62(const MillenniumAtariGemdosSelector62Observation o){return coordinator_.observe_millennium_atari_gemdos_selector_62(o);}
MillenniumAtariConfigConsumerResult LauncherRuntimeController::observe_millennium_atari_fread_prefix(const MillenniumAtariFreadPrefixObservation o){return coordinator_.observe_millennium_atari_fread_prefix(o);}
MillenniumAtariConfigConsumerResult LauncherRuntimeController::execute_millennium_atari_jsr_2b2be(){return coordinator_.execute_millennium_atari_jsr_2b2be();}
MillenniumAtariConfigConsumerResult LauncherRuntimeController::observe_millennium_atari_game_init_source_byte(const MillenniumAtariGameInitSourceByteObservation o){return coordinator_.observe_millennium_atari_game_init_source_byte(o);}
MillenniumAtariConfigConsumerResult LauncherRuntimeController::observe_millennium_atari_game_init_zero_pair(const MillenniumAtariGameInitZeroPairObservation o){return coordinator_.observe_millennium_atari_game_init_zero_pair(o);}
MillenniumAtariConfigConsumerResult LauncherRuntimeController::execute_millennium_atari_game_init_zero_counter_branch(){return coordinator_.execute_millennium_atari_game_init_zero_counter_branch();}
MillenniumAtariConfigConsumerResult LauncherRuntimeController::observe_millennium_atari_game_init_replicated_byte(const MillenniumAtariGameInitReplicatedByteObservation o){return coordinator_.observe_millennium_atari_game_init_replicated_byte(o);}
MillenniumAtariConfigConsumerResult LauncherRuntimeController::observe_millennium_atari_game_init_swapped_pair(const MillenniumAtariGameInitSwappedPairObservation o){return coordinator_.observe_millennium_atari_game_init_swapped_pair(o);}
MillenniumAtariConfigConsumerResult LauncherRuntimeController::observe_millennium_atari_game_init_extended_run(const MillenniumAtariGameInitExtendedRunObservation o){return coordinator_.observe_millennium_atari_game_init_extended_run(o);}
MillenniumAtariConfigConsumerResult LauncherRuntimeController::execute_millennium_atari_game_init_return(){return coordinator_.execute_millennium_atari_game_init_return();}
MillenniumAtariConfigConsumerResult LauncherRuntimeController::execute_millennium_atari_game_init_palette_copy_prefix(){return coordinator_.execute_millennium_atari_game_init_palette_copy_prefix();}
MillenniumAtariConfigConsumerResult LauncherRuntimeController::observe_millennium_atari_game_init_palette_words(const MillenniumAtariGameInitPaletteWordsObservation o){return coordinator_.observe_millennium_atari_game_init_palette_words(o);}
MillenniumAtariConfigConsumerResult LauncherRuntimeController::observe_millennium_atari_game_init_palette_xbios_selector_6(const MillenniumAtariGameInitPaletteXbios6Observation o){return coordinator_.observe_millennium_atari_game_init_palette_xbios_selector_6(o);}
MillenniumAtariConfigConsumerResult LauncherRuntimeController::observe_millennium_atari_game_init_palette_recurrence(const MillenniumAtariGameInitPaletteRecurrenceObservation o){return coordinator_.observe_millennium_atari_game_init_palette_recurrence(o);}
MillenniumAtariConfigConsumerResult LauncherRuntimeController::observe_millennium_atari_game_init_palette_rts(const MillenniumAtariGameInitPaletteRtsObservation o){return coordinator_.observe_millennium_atari_game_init_palette_rts(o);}
MillenniumAtariConfigConsumerResult LauncherRuntimeController::observe_millennium_atari_game_init_second_config_fopen(const MillenniumAtariGemdosSelector61Observation o){return coordinator_.observe_millennium_atari_game_init_second_config_fopen(o);}
MillenniumAtariConfigConsumerResult LauncherRuntimeController::observe_millennium_atari_game_init_second_config_fread(const MillenniumAtariGemdosSelector63Observation o){return coordinator_.observe_millennium_atari_game_init_second_config_fread(o);}
MillenniumAtariConfigConsumerResult LauncherRuntimeController::observe_millennium_atari_game_init_second_config_fclose(const MillenniumAtariGemdosSelector62Observation o){return coordinator_.observe_millennium_atari_game_init_second_config_fclose(o);}
MillenniumAtariConfigConsumerResult LauncherRuntimeController::observe_millennium_atari_game_init_second_config_rts(const MillenniumAtariGameInitSecondConfigRtsObservation o){return coordinator_.observe_millennium_atari_game_init_second_config_rts(o);}
MillenniumAtariConfigConsumerResult LauncherRuntimeController::observe_millennium_atari_game_init_second_config_xbios_38(const MillenniumAtariXbiosSelector38Observation o){return coordinator_.observe_millennium_atari_game_init_second_config_xbios_38(o);}
MillenniumAtariConfigConsumerResult LauncherRuntimeController::observe_millennium_atari_game_init_config_final_rts(const MillenniumAtariGameInitSecondConfigRtsObservation o){return coordinator_.observe_millennium_atari_game_init_config_final_rts(o);}
MillenniumAtariConfigConsumerResult LauncherRuntimeController::observe_millennium_atari_game_init_post_config_fopen(const MillenniumAtariGemdosSelector61Observation o){return coordinator_.observe_millennium_atari_game_init_post_config_fopen(o);}
MillenniumAtariConfigConsumerResult LauncherRuntimeController::observe_millennium_atari_game_init_post_config_fread(const MillenniumAtariGemdosSelector63Observation o){return coordinator_.observe_millennium_atari_game_init_post_config_fread(o);}
MillenniumAtariConfigConsumerResult LauncherRuntimeController::observe_millennium_atari_game_init_post_config_fclose(const MillenniumAtariGemdosSelector62Observation o){return coordinator_.observe_millennium_atari_game_init_post_config_fclose(o);}
MillenniumAtariConfigConsumerResult LauncherRuntimeController::observe_millennium_atari_game_init_post_config_rts(const MillenniumAtariGameInitSecondConfigRtsObservation o){return coordinator_.observe_millennium_atari_game_init_post_config_rts(o);}

std::optional<RuntimeSessionSnapshot> LauncherRuntimeController::session_snapshot() const {
    return coordinator_.session_snapshot();
}

MenuRuntimeLaunchResult launch_menu_runtime(const LauncherSessionState& session,
    const LaunchRequest& base, const std::vector<ReleaseArchive>& releases,
    ReleaseRuntimeCoordinator& coordinator) {
    // `launch_request` is the sole menu conversion: it carries the exact
    // game/platform/language/hash route and the selected presentation, but
    // has neither a source path nor an adapter.  The common gate below then
    // resolves that identity against this scanner snapshot and rehashes its
    // outer archive before publishing anything to SDL.
    const auto candidate = session.launch_request(base);
    const auto result = launch_runtime_candidate(candidate, releases, coordinator);
    return {{result.admission, result.rejection}, result.active_launch};
}

} // namespace eon
