#include "engine/millennium_dos_ninth_function_handoff_session.hpp"
#include "data/sha256.hpp"
#include <stdexcept>
namespace eon {
MillenniumDosNinthFunctionHandoffSession::MillenniumDosNinthFunctionHandoffSession(std::span<const std::uint8_t> e){if(to_hex(sha256(e))!="427574e5f780b2a7b5c4207d167116dc44aea3fb67096fbf12a46c4f544a0a57")throw std::runtime_error("Unsupported Millennium DOS F9 handoff profile");}
MillenniumDosNinthHandoffBoundary MillenniumDosNinthFunctionHandoffSession::boundary()const{switch(state_){case MillenniumDosNinthHandoffState::first_call:return{MillenniumDosNinthHandoffBoundaryKind::call_return,0x73cc,{},0x7bcb,loop_};case MillenniumDosNinthHandoffState::second_call:return{MillenniumDosNinthHandoffBoundaryKind::call_return,0x73cf,{},0xa2a0,loop_};case MillenniumDosNinthHandoffState::mode_byte:return{MillenniumDosNinthHandoffBoundaryKind::runtime_byte,0x73d2,0xda41,{}};case MillenniumDosNinthHandoffState::wait_call:return{MillenniumDosNinthHandoffBoundaryKind::call_return,0x73da,{},0x09fa,loop_};case MillenniumDosNinthHandoffState::wait_zero_flag:return{MillenniumDosNinthHandoffBoundaryKind::zero_flag,0x73dd,{},{},loop_};case MillenniumDosNinthHandoffState::wait_bl:return{MillenniumDosNinthHandoffBoundaryKind::register_bl,0x73df,{},{},loop_};case MillenniumDosNinthHandoffState::short_call:return{MillenniumDosNinthHandoffBoundaryKind::call_return,0x73e3,{},0x4111};case MillenniumDosNinthHandoffState::short_return:return{MillenniumDosNinthHandoffBoundaryKind::local_return,0x73e6,{},{}};case MillenniumDosNinthHandoffState::guard_word:return{MillenniumDosNinthHandoffBoundaryKind::runtime_word,0x73e7,0xa19e,{}};case MillenniumDosNinthHandoffState::optional_call:return{MillenniumDosNinthHandoffBoundaryKind::call_return,0x73ee,{},0x4111};case MillenniumDosNinthHandoffState::setup_first_call:return{MillenniumDosNinthHandoffBoundaryKind::call_return,0x73f1,{},0xbe28};case MillenniumDosNinthHandoffState::setup_second_call:return{MillenniumDosNinthHandoffBoundaryKind::call_return,0x73f4,{},0x0b9d};case MillenniumDosNinthHandoffState::cx_word:return{MillenniumDosNinthHandoffBoundaryKind::runtime_word,0x73f7,0x07da,{}};case MillenniumDosNinthHandoffState::setup_third_call:return{MillenniumDosNinthHandoffBoundaryKind::call_return,0x73fe,{},0x0ae3};case MillenniumDosNinthHandoffState::setup_fourth_call:return{MillenniumDosNinthHandoffBoundaryKind::call_return,0x7401,{},0x4bf7};case MillenniumDosNinthHandoffState::long_return:return{MillenniumDosNinthHandoffBoundaryKind::local_return,0x740e,{},{}};}throw std::runtime_error("Unsupported F9 handoff state");}
void MillenniumDosNinthFunctionHandoffSession::observe_call_return(std::uint16_t c,std::uint16_t r){auto b=boundary();if(b.kind!=MillenniumDosNinthHandoffBoundaryKind::call_return||b.instruction_address!=c||r!=std::uint16_t(c+3))throw std::runtime_error("Detached F9 handoff return");switch(state_){case MillenniumDosNinthHandoffState::first_call:state_=MillenniumDosNinthHandoffState::second_call;break;case MillenniumDosNinthHandoffState::second_call:state_=MillenniumDosNinthHandoffState::mode_byte;break;case MillenniumDosNinthHandoffState::wait_call:state_=MillenniumDosNinthHandoffState::wait_zero_flag;break;case MillenniumDosNinthHandoffState::short_call:state_=MillenniumDosNinthHandoffState::short_return;break;case MillenniumDosNinthHandoffState::optional_call:state_=MillenniumDosNinthHandoffState::setup_first_call;break;case MillenniumDosNinthHandoffState::setup_first_call:state_=MillenniumDosNinthHandoffState::setup_second_call;break;case MillenniumDosNinthHandoffState::setup_second_call:state_=MillenniumDosNinthHandoffState::cx_word;break;case MillenniumDosNinthHandoffState::setup_third_call:state_=MillenniumDosNinthHandoffState::setup_fourth_call;break;case MillenniumDosNinthHandoffState::setup_fourth_call:effects_.push_back({0x7404,0xda41,0});effects_.push_back({0x7409,0xda42,0x80});state_=MillenniumDosNinthHandoffState::long_return;break;default:throw std::runtime_error("Detached F9 handoff return");}}
void MillenniumDosNinthFunctionHandoffSession::observe_runtime_byte(std::uint16_t i,std::uint16_t a,std::uint8_t v){auto b=boundary();if(b.kind!=MillenniumDosNinthHandoffBoundaryKind::runtime_byte||b.instruction_address!=i||b.runtime_address!=a)throw std::runtime_error("Detached F9 handoff byte");state_=v?MillenniumDosNinthHandoffState::guard_word:MillenniumDosNinthHandoffState::wait_call;}
void MillenniumDosNinthFunctionHandoffSession::observe_runtime_word(std::uint16_t i,std::uint16_t a,std::uint16_t v){auto b=boundary();if(b.kind!=MillenniumDosNinthHandoffBoundaryKind::runtime_word||b.instruction_address!=i||b.runtime_address!=a)throw std::runtime_error("Detached F9 handoff word");if(state_==MillenniumDosNinthHandoffState::guard_word)state_=v?MillenniumDosNinthHandoffState::setup_first_call:MillenniumDosNinthHandoffState::optional_call;else state_=MillenniumDosNinthHandoffState::setup_third_call;}
void MillenniumDosNinthFunctionHandoffSession::observe_zero_flag(std::uint16_t i,bool z){if(state_!=MillenniumDosNinthHandoffState::wait_zero_flag||i!=0x73dd)throw std::runtime_error("Detached F9 handoff ZF");if(z){++loop_;state_=MillenniumDosNinthHandoffState::first_call;}else state_=MillenniumDosNinthHandoffState::wait_bl;}
void MillenniumDosNinthFunctionHandoffSession::observe_bl(std::uint16_t i,std::uint8_t v){if(state_!=MillenniumDosNinthHandoffState::wait_bl||i!=0x73df)throw std::runtime_error("Detached F9 handoff BL");if(v&1){++loop_;state_=MillenniumDosNinthHandoffState::first_call;}else state_=MillenniumDosNinthHandoffState::short_call;}
}
