#include "engine/millennium_dos_bdf_mode_two_session.hpp"
#include "data/sha256.hpp"
#include <stdexcept>
namespace eon{
MillenniumDosBdfModeTwoSession::MillenniumDosBdfModeTwoSession(std::span<const std::uint8_t>b,std::uint16_t di):entry_di_(di),current_offset_(di),destination_(di){if(to_hex(sha256(b))!="427574e5f780b2a7b5c4207d167116dc44aea3fb67096fbf12a46c4f544a0a57")throw std::runtime_error("Unsupported Millennium DOS $11f7 profile");}
std::uint16_t MillenniumDosBdfModeTwoSession::next_plane(std::uint16_t v){v=std::uint16_t(v+0x2000);return(v&0x8000)?std::uint16_t((v&0x7fff)+0x00a0):v;}
std::uint16_t MillenniumDosBdfModeTwoSession::rotate_right(std::uint16_t v){return std::uint16_t((v>>1)|(v<<15));}
MillenniumDosBdfModeTwoBoundary MillenniumDosBdfModeTwoSession::boundary()const{switch(state_){case MillenniumDosBdfModeTwoState::awaiting_toggle:return{0x11f7,0x07d8};case MillenniumDosBdfModeTwoState::awaiting_zero_segment:return{0x129d,0x0107};case MillenniumDosBdfModeTwoState::awaiting_zero_source_word:return{0x12af,source_};case MillenniumDosBdfModeTwoState::awaiting_nonzero_segment:return{0x1203,0x0107};case MillenniumDosBdfModeTwoState::awaiting_nonzero_far_word:return{0x1218,current_offset_,true,segment_};case MillenniumDosBdfModeTwoState::awaiting_transform_flag:return{0x123a,0x07da};case MillenniumDosBdfModeTwoState::awaiting_transform_bx_word:return{0x1251,std::uint16_t(0x0982+row_*2)};case MillenniumDosBdfModeTwoState::awaiting_transform_dx_word:return{0x1256,std::uint16_t(0x0962+row_*2)};case MillenniumDosBdfModeTwoState::awaiting_transform_far_byte:return{0x1263,current_offset_,true,segment_};case MillenniumDosBdfModeTwoState::returned:return{return_instruction_,0};}throw std::runtime_error("Invalid $11f7 state");}
void MillenniumDosBdfModeTwoSession::observe_runtime_byte(std::uint16_t i,std::uint16_t a,std::uint8_t v){if(state_!=MillenniumDosBdfModeTwoState::awaiting_toggle||i!=0x11f7||a!=0x07d8)throw std::runtime_error("Detached $11f7 byte");if(v){destination_=0x07fa;state_=MillenniumDosBdfModeTwoState::awaiting_nonzero_segment;}else state_=MillenniumDosBdfModeTwoState::awaiting_zero_segment;}
void MillenniumDosBdfModeTwoSession::observe_runtime_word(std::uint16_t i,std::uint16_t a,std::uint16_t v){if(state_==MillenniumDosBdfModeTwoState::awaiting_zero_segment||state_==MillenniumDosBdfModeTwoState::awaiting_nonzero_segment){const bool nonzero=state_==MillenniumDosBdfModeTwoState::awaiting_nonzero_segment;const auto expected=std::uint16_t(nonzero?0x1203:0x129d);if(i!=expected||a!=0x0107)throw std::runtime_error("Detached $11f7 segment");segment_=v;state_=nonzero?MillenniumDosBdfModeTwoState::awaiting_nonzero_far_word:MillenniumDosBdfModeTwoState::awaiting_zero_source_word;return;}if(state_==MillenniumDosBdfModeTwoState::awaiting_transform_flag){if(i!=0x123a||a!=0x07da)throw std::runtime_error("Detached $11f7 transform flag");transform_flag_=std::uint8_t(v&1);state_=MillenniumDosBdfModeTwoState::awaiting_transform_bx_word;return;}if(state_==MillenniumDosBdfModeTwoState::awaiting_transform_bx_word){if(i!=0x1251||a!=std::uint16_t(0x0982+row_*2))throw std::runtime_error("Detached $11f7 BX word");bx_=std::uint16_t((v>>8)|(v<<8));state_=MillenniumDosBdfModeTwoState::awaiting_transform_dx_word;return;}if(state_==MillenniumDosBdfModeTwoState::awaiting_transform_dx_word){if(i!=0x1256||a!=std::uint16_t(0x0962+row_*2))throw std::runtime_error("Detached $11f7 DX word");dx_=std::uint16_t((v>>8)|(v<<8));if(transform_flag_){bx_=rotate_right(bx_);dx_=rotate_right(dx_);}state_=MillenniumDosBdfModeTwoState::awaiting_transform_far_byte;return;}if(state_!=MillenniumDosBdfModeTwoState::awaiting_zero_source_word||i!=0x12af||a!=source_)throw std::runtime_error("Detached $11f7 source word");far_effects_.push_back({0x12af,segment_,current_offset_,v});source_=std::uint16_t(source_+2);current_offset_=std::uint16_t(current_offset_+2);advance_zero();}
void MillenniumDosBdfModeTwoSession::observe_far_word(std::uint16_t i,std::uint16_t s,std::uint16_t o,std::uint16_t v){if(state_!=MillenniumDosBdfModeTwoState::awaiting_nonzero_far_word||i!=0x1218||s!=segment_||o!=current_offset_)throw std::runtime_error("Detached $11f7 far word");runtime_effects_.push_back({0x1218,destination_,v});destination_=std::uint16_t(destination_+2);current_offset_=std::uint16_t(current_offset_+2);advance_nonzero();}
void MillenniumDosBdfModeTwoSession::advance_zero(){if(++word_!=4)return;word_=0;current_offset_=next_plane(std::uint16_t(current_offset_-8));if(++row_==16){return_instruction_=0x12cb;state_=MillenniumDosBdfModeTwoState::returned;}}
void MillenniumDosBdfModeTwoSession::advance_nonzero(){if(++word_!=4)return;word_=0;current_offset_=next_plane(std::uint16_t(current_offset_-8));if(++row_==16){row_=0;current_offset_=entry_di_;state_=MillenniumDosBdfModeTwoState::awaiting_transform_flag;}}
void MillenniumDosBdfModeTwoSession::observe_far_byte(std::uint16_t i,std::uint16_t s,std::uint16_t o,std::uint8_t v){if(state_!=MillenniumDosBdfModeTwoState::awaiting_transform_far_byte||i!=0x1263||s!=segment_||o!=current_offset_)throw std::runtime_error("Detached $11f7 transform byte");auto al=v;const bool bx1=(bx_&0x8000)!=0;bx_=std::uint16_t(bx_<<1);if(!bx1)al&=0x0f;const bool dx1=(dx_&0x8000)!=0;dx_=std::uint16_t(dx_<<1);if(dx1)al|=0xf0;const bool bx2=(bx_&0x8000)!=0;bx_=std::uint16_t(bx_<<1);if(!bx2)al&=0xf0;const bool dx2=(dx_&0x8000)!=0;dx_=std::uint16_t(dx_<<1);if(dx2)al|=0x0f;far_byte_effects_.push_back({0x127e,segment_,current_offset_,al});current_offset_=std::uint16_t(current_offset_+1);if(++pixel_!=8)return;pixel_=0;current_offset_=next_plane(std::uint16_t(current_offset_-8));if(++row_==16){return_instruction_=0x129c;state_=MillenniumDosBdfModeTwoState::returned;}else state_=MillenniumDosBdfModeTwoState::awaiting_transform_bx_word;}
}
