#include "engine/millennium_dos_bdf_service_session.hpp"
#include "data/sha256.hpp"
#include <stdexcept>
namespace eon{
MillenniumDosBdfServiceSession::MillenniumDosBdfServiceSession(std::span<const std::uint8_t>e){if(to_hex(sha256(e))!="427574e5f780b2a7b5c4207d167116dc44aea3fb67096fbf12a46c4f544a0a57")throw std::runtime_error("Unsupported Millennium DOS $0bdf profile");}
MillenniumDosBdfServiceBoundary MillenniumDosBdfServiceSession::boundary()const{switch(state_){case MillenniumDosBdfServiceState::awaiting_active_byte:return{MillenniumDosBdfServiceBoundaryKind::runtime_byte,0x0bdf,0x07d8,{}};case MillenniumDosBdfServiceState::returned_by_active:return{MillenniumDosBdfServiceBoundaryKind::local_return,0x0be6,{},{}};case MillenniumDosBdfServiceState::awaiting_segment_word:return{MillenniumDosBdfServiceBoundaryKind::runtime_word,0x0bed,0x0107,{}};case MillenniumDosBdfServiceState::awaiting_source_word:return{MillenniumDosBdfServiceBoundaryKind::runtime_word,0x0bf2,0x07d6,{}};case MillenniumDosBdfServiceState::awaiting_toggle_byte:return{MillenniumDosBdfServiceBoundaryKind::runtime_byte,0x0bf6,0x07d8,{}};case MillenniumDosBdfServiceState::awaiting_poll_return:return{MillenniumDosBdfServiceBoundaryKind::call_return,0x0c0a,{},0x09fa};case MillenniumDosBdfServiceState::awaiting_mode_byte:return{MillenniumDosBdfServiceBoundaryKind::runtime_byte,0x0c19,0xda05,{}};}throw std::runtime_error("Unsupported Millennium DOS $0bdf state");}
void MillenniumDosBdfServiceSession::observe_runtime_byte(std::uint16_t i,std::uint16_t a,std::uint8_t v){auto b=boundary();if(b.kind!=MillenniumDosBdfServiceBoundaryKind::runtime_byte||b.instruction_address!=i||b.runtime_address!=a)throw std::runtime_error("Detached $0bdf byte");if(state_==MillenniumDosBdfServiceState::awaiting_active_byte){initial_toggle_=v;state_=v?MillenniumDosBdfServiceState::returned_by_active:MillenniumDosBdfServiceState::awaiting_segment_word;return;}if(state_==MillenniumDosBdfServiceState::awaiting_toggle_byte){if(v!=initial_toggle_)throw std::runtime_error("Changed $0bdf toggle between exact reads");const auto toggled=std::uint8_t(v^1);effects_.push_back({0x0bfb,0x07d8,1,toggled});state_=toggled?MillenniumDosBdfServiceState::awaiting_poll_return:MillenniumDosBdfServiceState::awaiting_mode_byte;return;}throw std::runtime_error("Unimplemented $0bdf mode continuation");}
void MillenniumDosBdfServiceSession::observe_runtime_word(std::uint16_t i,std::uint16_t a,std::uint16_t){auto b=boundary();if(b.kind!=MillenniumDosBdfServiceBoundaryKind::runtime_word||b.instruction_address!=i||b.runtime_address!=a)throw std::runtime_error("Detached $0bdf word");state_=state_==MillenniumDosBdfServiceState::awaiting_segment_word?MillenniumDosBdfServiceState::awaiting_source_word:MillenniumDosBdfServiceState::awaiting_toggle_byte;}
void MillenniumDosBdfServiceSession::observe_poll_return(std::uint16_t c,std::uint16_t r,std::uint16_t cx,std::uint16_t dx){if(state_!=MillenniumDosBdfServiceState::awaiting_poll_return||c!=0x0c0a||r!=0x0c0d)throw std::runtime_error("Detached $0bdf poll return");effects_.push_back({0x0c0f,0x07da,2,cx});effects_.push_back({0x0c13,0x07dc,2,dx});state_=MillenniumDosBdfServiceState::awaiting_mode_byte;}
}
