#include "engine/millennium_dos_fourth_function_session.hpp"
#include <stdexcept>
namespace eon {
MillenniumDosFourthFunctionSession::MillenniumDosFourthFunctionSession(std::span<const std::uint8_t> executable):trace_(parse_millennium_dos_game_flow(executable).fourth_function_key){
 if(trace_.handler_address!=0x72f9||trace_.initialization_guard_address!=0xa19e||trace_.transfer_al_value!=2||trace_.common_routine_address!=0xba5e||trace_.first_call_address!=0x4d2c||trace_.first_write_instruction_address!=0xba64||trace_.second_call_address!=0x9dd5||trace_.second_write_instruction_address!=0xba6c||trace_.common_return_instruction_address!=0xba76) throw std::runtime_error("Unsupported Millennium DOS fourth-function profile");
}
MillenniumDosFourthFunctionBoundary MillenniumDosFourthFunctionSession::boundary() const{
 switch(state_){case MillenniumDosFourthFunctionState::awaiting_guard:return {MillenniumDosFourthFunctionBoundaryKind::runtime_word,0x72f9,trace_.initialization_guard_address,std::nullopt,std::nullopt};case MillenniumDosFourthFunctionState::awaiting_first_return:return {MillenniumDosFourthFunctionBoundaryKind::call_return,0xba61,std::nullopt,trace_.first_call_address,std::uint16_t{5}};case MillenniumDosFourthFunctionState::awaiting_second_return:return {MillenniumDosFourthFunctionBoundaryKind::call_return,0xba69,std::nullopt,trace_.second_call_address,std::nullopt};case MillenniumDosFourthFunctionState::returned_by_guard:return {MillenniumDosFourthFunctionBoundaryKind::local_return,0x7300,std::nullopt,std::nullopt,std::nullopt};case MillenniumDosFourthFunctionState::returned:return {MillenniumDosFourthFunctionBoundaryKind::local_return,trace_.common_return_instruction_address,std::nullopt,std::nullopt,std::nullopt};} throw std::runtime_error("Unsupported fourth-function state");
}
void MillenniumDosFourthFunctionSession::observe_runtime_word(std::uint16_t i,std::uint16_t a,std::uint16_t v){auto b=boundary();if(b.kind!=MillenniumDosFourthFunctionBoundaryKind::runtime_word||b.instruction_address!=i||b.runtime_address!=a)throw std::runtime_error("Detached fourth-function word");state_=v?MillenniumDosFourthFunctionState::returned_by_guard:MillenniumDosFourthFunctionState::awaiting_first_return;}
void MillenniumDosFourthFunctionSession::observe_call_return(std::uint16_t c,std::uint16_t r){auto b=boundary();if(b.kind!=MillenniumDosFourthFunctionBoundaryKind::call_return||b.instruction_address!=c||r!=static_cast<std::uint16_t>(c+3U))throw std::runtime_error("Detached fourth-function return");if(state_==MillenniumDosFourthFunctionState::awaiting_first_return){effects_.push_back({trace_.first_write_instruction_address,trace_.first_runtime_byte_address,trace_.first_runtime_byte_value});state_=MillenniumDosFourthFunctionState::awaiting_second_return;}else{effects_.push_back({trace_.second_write_instruction_address,trace_.second_runtime_byte_address,trace_.second_runtime_byte_value});effects_.push_back({0xba71,trace_.third_runtime_byte_address,trace_.third_runtime_byte_value});state_=MillenniumDosFourthFunctionState::returned;}}
} // namespace eon
