#include "engine/millennium_dos_second_function_callback_session.hpp"
#include "data/sha256.hpp"
#include <stdexcept>
namespace eon {
MillenniumDosSecondFunctionCallbackSession::MillenniumDosSecondFunctionCallbackSession(std::span<const std::uint8_t> e):trace_(parse_millennium_dos_game_flow(e).second_function_key){if(to_hex(sha256(e))!="427574e5f780b2a7b5c4207d167116dc44aea3fb67096fbf12a46c4f544a0a57"||trace_.callback_address!=0x7221||trace_.record_list_address!=0x6e99||trace_.availability_address!=0xda26)throw std::runtime_error("Unsupported Millennium DOS F2 callback profile");}
MillenniumDosSecondFunctionCallbackBoundary MillenniumDosSecondFunctionCallbackSession::boundary()const{switch(state_){case MillenniumDosSecondFunctionCallbackState::awaiting_selection_byte:return{MillenniumDosSecondFunctionCallbackBoundaryKind::runtime_byte,0x7221,0x6e93,{}};case MillenniumDosSecondFunctionCallbackState::external_reset_jump:return{MillenniumDosSecondFunctionCallbackBoundaryKind::external_jump,0x7228,{},0x702c};case MillenniumDosSecondFunctionCallbackState::awaiting_record_pointer:return{MillenniumDosSecondFunctionCallbackBoundaryKind::runtime_word,0x7237,pointer_cell_,{}};case MillenniumDosSecondFunctionCallbackState::awaiting_first_call_return:return{MillenniumDosSecondFunctionCallbackBoundaryKind::call_return,0x723b,{},0x0bd7};case MillenniumDosSecondFunctionCallbackState::awaiting_second_call_return:return{MillenniumDosSecondFunctionCallbackBoundaryKind::call_return,0x723e,{},0x4bf7};case MillenniumDosSecondFunctionCallbackState::awaiting_wait_return:return{MillenniumDosSecondFunctionCallbackBoundaryKind::call_return,0x7241,{},0x09fa,wait_iteration_};case MillenniumDosSecondFunctionCallbackState::awaiting_wait_bl:return{MillenniumDosSecondFunctionCallbackBoundaryKind::register_bl,0x7244,{},{},wait_iteration_};case MillenniumDosSecondFunctionCallbackState::awaiting_third_call_return:return{MillenniumDosSecondFunctionCallbackBoundaryKind::call_return,0x7248,{},0x0b0c};case MillenniumDosSecondFunctionCallbackState::awaiting_fourth_call_return:return{MillenniumDosSecondFunctionCallbackBoundaryKind::call_return,0x7250,{},0x7728};case MillenniumDosSecondFunctionCallbackState::external_tail_jump:return{MillenniumDosSecondFunctionCallbackBoundaryKind::external_jump,0x7253,{},0x0bdf};}throw std::runtime_error("Unsupported Millennium DOS F2 callback state");}
void MillenniumDosSecondFunctionCallbackSession::observe_runtime_byte(std::uint16_t i,std::uint16_t a,std::uint8_t v){auto b=boundary();if(b.kind!=MillenniumDosSecondFunctionCallbackBoundaryKind::runtime_byte||b.instruction_address!=i||b.runtime_address!=a)throw std::runtime_error("Detached Millennium DOS F2 callback byte");const auto selected=std::uint8_t(v+1);if(selected==0){state_=MillenniumDosSecondFunctionCallbackState::external_reset_jump;return;}effects_.push_back({0x722d,0xda1f,1,selected});pointer_cell_=static_cast<std::uint16_t>(0x27c4+2*selected);state_=MillenniumDosSecondFunctionCallbackState::awaiting_record_pointer;}
void MillenniumDosSecondFunctionCallbackSession::observe_runtime_word(std::uint16_t i,std::uint16_t a,std::uint16_t v){auto b=boundary();if(b.kind!=MillenniumDosSecondFunctionCallbackBoundaryKind::runtime_word||b.instruction_address!=i||b.runtime_address!=a)throw std::runtime_error("Detached Millennium DOS F2 callback word");effects_.push_back({0x7238,0xda20,2,v});state_=MillenniumDosSecondFunctionCallbackState::awaiting_first_call_return;}
void MillenniumDosSecondFunctionCallbackSession::observe_call_return(std::uint16_t c,std::uint16_t r){auto b=boundary();if(b.kind!=MillenniumDosSecondFunctionCallbackBoundaryKind::call_return||b.instruction_address!=c||r!=std::uint16_t(c+3))throw std::runtime_error("Detached Millennium DOS F2 callback return");switch(state_){case MillenniumDosSecondFunctionCallbackState::awaiting_first_call_return:state_=MillenniumDosSecondFunctionCallbackState::awaiting_second_call_return;break;case MillenniumDosSecondFunctionCallbackState::awaiting_second_call_return:state_=MillenniumDosSecondFunctionCallbackState::awaiting_wait_return;break;case MillenniumDosSecondFunctionCallbackState::awaiting_wait_return:state_=MillenniumDosSecondFunctionCallbackState::awaiting_wait_bl;break;case MillenniumDosSecondFunctionCallbackState::awaiting_third_call_return:effects_.push_back({0x724b,0xda1e,1,0});state_=MillenniumDosSecondFunctionCallbackState::awaiting_fourth_call_return;break;case MillenniumDosSecondFunctionCallbackState::awaiting_fourth_call_return:state_=MillenniumDosSecondFunctionCallbackState::external_tail_jump;break;default:throw std::runtime_error("Detached Millennium DOS F2 callback return");}}
void MillenniumDosSecondFunctionCallbackSession::observe_bl(std::uint16_t i,std::uint8_t v){if(state_!=MillenniumDosSecondFunctionCallbackState::awaiting_wait_bl||i!=0x7244)throw std::runtime_error("Detached Millennium DOS F2 callback BL");if(v&1){++wait_iteration_;state_=MillenniumDosSecondFunctionCallbackState::awaiting_wait_return;}else state_=MillenniumDosSecondFunctionCallbackState::awaiting_third_call_return;}
}
