#include "engine/millennium_dos_bdf_other_mode_session.hpp"
#include "data/sha256.hpp"
#include <stdexcept>
namespace eon {
MillenniumDosBdfOtherModeSession::MillenniumDosBdfOtherModeSession(std::span<const std::uint8_t>b,std::uint8_t dl,std::uint16_t di):state_(dl==4?MillenniumDosBdfOtherModeState::awaiting_mode_four_toggle:MillenniumDosBdfOtherModeState::awaiting_toggle),entry_di_(di){if(to_hex(sha256(b))!="427574e5f780b2a7b5c4207d167116dc44aea3fb67096fbf12a46c4f544a0a57")throw std::runtime_error("Unsupported Millennium DOS $0caa profile");}
MillenniumDosBdfOtherModeBoundary MillenniumDosBdfOtherModeSession::boundary()const{switch(state_){case MillenniumDosBdfOtherModeState::awaiting_toggle:return{0x0cb2,0x07d8};case MillenniumDosBdfOtherModeState::awaiting_segment:return{0x0d3e,0x0107};case MillenniumDosBdfOtherModeState::awaiting_source_word:return{0x0d56,source_};case MillenniumDosBdfOtherModeState::awaiting_mode_four_toggle:return{0x0d68,0x07d8};case MillenniumDosBdfOtherModeState::mode_four_nonzero_boundary:return{0x0d74,0};case MillenniumDosBdfOtherModeState::awaiting_mode_four_segment:return{0x0e29,0x0107};case MillenniumDosBdfOtherModeState::awaiting_mode_four_source_word:return{0x0e41,source_};case MillenniumDosBdfOtherModeState::awaiting_mode_four_source_byte:return{0x0e42,source_};case MillenniumDosBdfOtherModeState::returned:return{return_instruction_,0};}throw std::runtime_error("Invalid $0caa state");}
void MillenniumDosBdfOtherModeSession::observe_runtime_byte(std::uint16_t i,std::uint16_t a,std::uint8_t v){if(state_==MillenniumDosBdfOtherModeState::awaiting_toggle){if(i!=0x0cb2||a!=0x07d8)throw std::runtime_error("Detached $0caa byte");if(v)throw std::runtime_error("$0cbe nonzero path remains outside this session");state_=MillenniumDosBdfOtherModeState::awaiting_segment;return;}if(state_==MillenniumDosBdfOtherModeState::awaiting_mode_four_toggle){if(i!=0x0d68||a!=0x07d8)throw std::runtime_error("Detached $0d68 byte");state_=v?MillenniumDosBdfOtherModeState::mode_four_nonzero_boundary:MillenniumDosBdfOtherModeState::awaiting_mode_four_segment;return;}if(state_==MillenniumDosBdfOtherModeState::awaiting_mode_four_source_byte){if(i!=0x0e42||a!=source_)throw std::runtime_error("Detached $0e42 byte");far_byte_effects_.push_back({0x0e42,segment_,std::uint16_t(entry_di_+row_*0x50+2),v});++source_;if(++row_!=16){state_=MillenniumDosBdfOtherModeState::awaiting_mode_four_source_word;return;}row_=0;if(++plane_==4){return_instruction_=0x0e53;state_=MillenniumDosBdfOtherModeState::returned;return;}port_effects_.push_back({0x0e40,0x03c5,std::uint8_t(1u<<plane_)});state_=MillenniumDosBdfOtherModeState::awaiting_mode_four_source_word;return;}throw std::runtime_error("Unsupported $0caa byte state");}
void MillenniumDosBdfOtherModeSession::observe_runtime_word(std::uint16_t i,std::uint16_t a,std::uint16_t v){if(state_==MillenniumDosBdfOtherModeState::awaiting_segment){if(i!=0x0d3e||a!=0x0107)throw std::runtime_error("Detached $0caa segment");segment_=v;port_effects_.push_back({0x0d55,0x03c5,1});state_=MillenniumDosBdfOtherModeState::awaiting_source_word;return;}if(state_==MillenniumDosBdfOtherModeState::awaiting_mode_four_segment){if(i!=0x0e29||a!=0x0107)throw std::runtime_error("Detached $0e29 segment");segment_=v;port_effects_.push_back({0x0e40,0x03c5,1});state_=MillenniumDosBdfOtherModeState::awaiting_mode_four_source_word;return;}if(state_==MillenniumDosBdfOtherModeState::awaiting_mode_four_source_word){if(i!=0x0e41||a!=source_)throw std::runtime_error("Detached $0e41 word");far_effects_.push_back({0x0e41,segment_,std::uint16_t(entry_di_+row_*0x50),v});source_=std::uint16_t(source_+2);state_=MillenniumDosBdfOtherModeState::awaiting_mode_four_source_byte;return;}if(state_!=MillenniumDosBdfOtherModeState::awaiting_source_word||i!=0x0d56||a!=source_)throw std::runtime_error("Detached $0caa source word");far_effects_.push_back({0x0d56,segment_,std::uint16_t(entry_di_+row_*0x28),v});source_=std::uint16_t(source_+2);if(++row_!=16)return;row_=0;if(++plane_==4){return_instruction_=0x0d67;state_=MillenniumDosBdfOtherModeState::returned;return;}port_effects_.push_back({0x0d55,0x03c5,std::uint8_t(1u<<plane_)});}
}
