#include "engine/millennium_dos_bdf_service_session.hpp"
#include "data/sha256.hpp"
#include <stdexcept>
namespace eon{
MillenniumDosBdfServiceSession::MillenniumDosBdfServiceSession(std::span<const std::uint8_t>e){if(to_hex(sha256(e))!="427574e5f780b2a7b5c4207d167116dc44aea3fb67096fbf12a46c4f544a0a57")throw std::runtime_error("Unsupported Millennium DOS $0bdf profile");}
MillenniumDosBdfServiceBoundary MillenniumDosBdfServiceSession::boundary()const{switch(state_){case MillenniumDosBdfServiceState::awaiting_active_byte:return{MillenniumDosBdfServiceBoundaryKind::runtime_byte,0x0bdf,0x07d8,{},{}};case MillenniumDosBdfServiceState::returned_by_active:return{MillenniumDosBdfServiceBoundaryKind::local_return,0x0be6,{},{},{}};case MillenniumDosBdfServiceState::awaiting_segment_word:return{MillenniumDosBdfServiceBoundaryKind::runtime_word,0x0bed,0x0107,{},{}};case MillenniumDosBdfServiceState::awaiting_source_word:return{MillenniumDosBdfServiceBoundaryKind::runtime_word,0x0bf2,0x07d6,{},{}};case MillenniumDosBdfServiceState::awaiting_toggle_byte:return{MillenniumDosBdfServiceBoundaryKind::runtime_byte,0x0bf6,0x07d8,{},{}};case MillenniumDosBdfServiceState::awaiting_poll_return:return{MillenniumDosBdfServiceBoundaryKind::call_return,0x0c0a,{},0x09fa,{}};case MillenniumDosBdfServiceState::awaiting_mode_byte:return{MillenniumDosBdfServiceBoundaryKind::runtime_byte,0x0c19,0xda05,{},{}};case MillenniumDosBdfServiceState::awaiting_mapping_return:return{MillenniumDosBdfServiceBoundaryKind::call_return,0x0c34,{},0x04ef,computed_ax_};case MillenniumDosBdfServiceState::awaiting_second_mode_byte:return{MillenniumDosBdfServiceBoundaryKind::runtime_byte,0x0c3c,0xda05,{},{}};case MillenniumDosBdfServiceState::external_mode_two_jump:return{MillenniumDosBdfServiceBoundaryKind::external_jump,0x0c4b,{},0x11f7,{}};case MillenniumDosBdfServiceState::external_other_mode_jump:return{MillenniumDosBdfServiceBoundaryKind::external_jump,0x0c4e,{},0x0caa,{}};case MillenniumDosBdfServiceState::awaiting_copy_toggle_byte:return{MillenniumDosBdfServiceBoundaryKind::runtime_byte,0x0c51,0x07d8,{},{}};case MillenniumDosBdfServiceState::far_memory_nonzero_boundary:return{MillenniumDosBdfServiceBoundaryKind::far_memory,0x0c6d,{},{},{}};case MillenniumDosBdfServiceState::far_memory_zero_boundary:return{MillenniumDosBdfServiceBoundaryKind::far_memory,0x0c8b,{},{},{}};}throw std::runtime_error("Unsupported Millennium DOS $0bdf state");}
void MillenniumDosBdfServiceSession::observe_runtime_byte(std::uint16_t i,std::uint16_t a,std::uint8_t v){auto b=boundary();if(b.kind!=MillenniumDosBdfServiceBoundaryKind::runtime_byte||b.instruction_address!=i||b.runtime_address!=a)throw std::runtime_error("Detached $0bdf byte");if(state_==MillenniumDosBdfServiceState::awaiting_active_byte){initial_toggle_=v;state_=v?MillenniumDosBdfServiceState::returned_by_active:MillenniumDosBdfServiceState::awaiting_segment_word;return;}if(state_==MillenniumDosBdfServiceState::awaiting_toggle_byte){if(v!=initial_toggle_)throw std::runtime_error("Changed $0bdf toggle between exact reads");const auto toggled=std::uint8_t(v^1);effects_.push_back({0x0bfb,0x07d8,1,toggled});state_=toggled?MillenniumDosBdfServiceState::awaiting_poll_return:MillenniumDosBdfServiceState::awaiting_mode_byte;return;}if(state_==MillenniumDosBdfServiceState::awaiting_mode_byte){computed_ax_=observed_cx_;if(v==3)computed_ax_>>=1;if(v==3||v==4)computed_ax_>>=2;state_=MillenniumDosBdfServiceState::awaiting_mapping_return;return;}if(state_==MillenniumDosBdfServiceState::awaiting_second_mode_byte){state_=v==1?MillenniumDosBdfServiceState::awaiting_copy_toggle_byte:v==2?MillenniumDosBdfServiceState::external_mode_two_jump:MillenniumDosBdfServiceState::external_other_mode_jump;return;}if(state_==MillenniumDosBdfServiceState::awaiting_copy_toggle_byte){state_=v?MillenniumDosBdfServiceState::far_memory_nonzero_boundary:MillenniumDosBdfServiceState::far_memory_zero_boundary;return;}throw std::runtime_error("Unsupported $0bdf byte state");}
void MillenniumDosBdfServiceSession::observe_runtime_word(std::uint16_t i,std::uint16_t a,std::uint16_t){auto b=boundary();if(b.kind!=MillenniumDosBdfServiceBoundaryKind::runtime_word||b.instruction_address!=i||b.runtime_address!=a)throw std::runtime_error("Detached $0bdf word");state_=state_==MillenniumDosBdfServiceState::awaiting_segment_word?MillenniumDosBdfServiceState::awaiting_source_word:MillenniumDosBdfServiceState::awaiting_toggle_byte;}
void MillenniumDosBdfServiceSession::observe_poll_return(std::uint16_t c,std::uint16_t r,std::uint16_t cx,std::uint16_t dx){if(state_!=MillenniumDosBdfServiceState::awaiting_poll_return||c!=0x0c0a||r!=0x0c0d)throw std::runtime_error("Detached $0bdf poll return");observed_cx_=cx;effects_.push_back({0x0c0f,0x07da,2,cx});effects_.push_back({0x0c13,0x07dc,2,dx});state_=MillenniumDosBdfServiceState::awaiting_mode_byte;}
void MillenniumDosBdfServiceSession::observe_mapping_return(std::uint16_t c,std::uint16_t r,std::uint16_t){if(state_!=MillenniumDosBdfServiceState::awaiting_mapping_return||c!=0x0c34||r!=0x0c37)throw std::runtime_error("Detached $0bdf mapping return");state_=MillenniumDosBdfServiceState::awaiting_second_mode_byte;}
}
